import { ReactNode } from "react";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { Providers } from "../redux/Provider";
import ProviderReactQuery from "../react-query/Provider";

export const metadata = {
  title: "InforCFC",
  description: "Generated by Next.js",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ProviderReactQuery>
            {children}
          </ProviderReactQuery>  
        </Providers>
      </body>
    </html>
  );
}
